import type { Metadata } from "next";
import { Urbanist } from "next/font/google";
import "./globals.css";
import Header from "@/components/ui/header";
import Footer from "@/components/ui/footer";
import NextTopLoader from "nextjs-toploader";
import ChatBot from "@/components/chatbot/chatbot";

const urbanist = Urbanist({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Sekwoja - Meble na wymiar",
  description: "Generated by create next app",
};

export const revalidate = 3600;

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={urbanist.className}>
        <Header />
        <main className="min-h-[calc(100vh-7rem)] flex flex-col">
          {children}
        </main>
        <Footer />
        <NextTopLoader color="#019843" />
        <ChatBot />
      </body>
    </html>
  );
}
